server {
    listen 8080;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    # React Router: cualquier ruta que no sea un archivo real cae a index.html
    location / {
        try_files $uri $uri/ /index.html;
    }
}
